version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 2443:2443
      - 9229:9229
    command: npm run start:dev
    restart: always

volumes:
  pgdata: